### **Задание на повторение материала

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.

In [246]:
import numpy as np

In [247]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [248]:
#1
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [249]:
#2
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [250]:
#3
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [251]:
#4
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [252]:
#5
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [253]:
#1
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [254]:
#2
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [255]:
#3
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [256]:
#4
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [257]:
#5
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [258]:
# Нет, массив двумерный

a.resize(12, 1)
a.ndim

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [259]:
b = np.random.randn(3, 4)

print(b)

[[ 1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112  0.31424733]]


In [260]:
b1 = b.flatten()

b.size == b1.size

True

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [261]:
a = np.arange(20, 0, -2)

print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [262]:
b = np.arange(20, 1, -2)

print(b)

[20 18 16 14 12 10  8  6  4  2]


In [263]:
#Массивы a и b одинаковы.

np.array_equal(a, b)

True

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [264]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

print('Массив а\n{}'.format(a), '\n')
print('Массив b\n{}'.format(b))

Массив а
[[0. 0.]
 [0. 0.]] 

Массив b
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [265]:
v = np.vstack((a, b))

print('Массив v\n{}'.format(v), '\n')
print('v size: {}'.format(v.size))

Массив v
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

v size: 10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [266]:
a = np.arange(0, 12)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [267]:
A = a.reshape(4, 3)

print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [268]:
At = A.transpose()

print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [269]:
B = A.dot(At)

print('Матрица B \n{}'.format(B), '\n')
print('Матрица B - квадратная: {}'.format(B.shape))

Матрица B 
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]] 

Матрица B - квадратная: (4, 4)


Ответ: Обратную матрицу можно посчитать только для квадратной матрицы, определитель которой отличен от нуля. Матрицу B обращать нельзя, т.к. ее определитель равен 0.

In [270]:
np.linalg.det(B)

0.0

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [271]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [272]:
c = np.random.randint(0, 16, 16)

print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [273]:
C = c.reshape(4, 4)

print(C)

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [274]:
C.shape == B.shape

True

In [275]:
D = np.add(B, (np.multiply(C, 10)))

print(D)

[[ 65  44 143 172]
 [114 120 206 162]
 [ 83 176 169 272]
 [132 222 282 342]]


In [276]:
print('Определитель D: {}'.format(np.linalg.det(D)))

Определитель D: -28511999.999999944


In [277]:
print('Ранг D: {}'.format(np.linalg.matrix_rank(D)))

Ранг D: 4


In [278]:
D_inv = np.linalg.inv(D)

print('Обратная матрица D_inv: \n{}'.format(D_inv))

Обратная матрица D_inv: 
[[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [279]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
print(D_inv)

[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]


In [280]:
np.where(D_inv, B, C)

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])